apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: train-ingress
  namespace: int-apis
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - train.k8test.net
    secretName: k8test-secret
  rules:
  - host: train.k8test.net
    http:
      paths:
      - path: /
        backend:
          serviceName: train-schedule-service
          servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: priv-docker
